language: cpp
sudo: false
branches:
  except:
    - /^(wip\/)?(appveyor|msvc|mingw|windows)(\-.+)?$/

addons:
  apt:
    sources: &default_sources
      - ubuntu-toolchain-r-test
    packages: &default_pacakges
      - nasm 
      
env:
  global:
    - GLOBAL=value

matrix:
  include:
      # clang-5.0 is the default installed on travis VMs
    - compiler: clang-5.0
      env: TRUE_CC=clang-5.0 TRUE_CXX=clang++-5.0 CXXFLAGS=-stdlib=libc++
      addons:
        apt:
          packages:
            - *default_pacakges
            - clang++-5.0
            - libc++abi1
            - libc++1
    - compiler: gcc-4.9
      env: TRUE_CC=gcc-4.9 TRUE_CXX=g++-4.9
      addons:
        apt:
          sources:
          - *default_sources
          packages:
          - *default_pacakges
          - gcc-4.9
          - g++-4.9
    - compiler: gcc-6
      env: TRUE_CC=gcc-6 TRUE_CXX=g++-6
      addons:
        apt:
          sources:
          - *default_sources
          packages:
          - *default_pacakges
          - gcc-6
          - g++-6
    - compiler: clang-6.0
      env: TRUE_CC=clang-6.0 TRUE_CXX=clang++-6.0
      addons:
        apt:
          sources:
          - llvm-toolchain-trusty-6.0
          - ubuntu-toolchain-r-test
          packages:
          - *default_pacakges
          - clang-6.0
          - clang++-6.0

before_install:
# The TravisCI framework will set CC and CXX after the env commands specified in the matrix are run, overwriting whatever
# we've specified there, so we need to reset them here. See also https://github.com/travis-ci/travis-ci/issues/6633 . 
  - CC=${TRUE_CC:-$CC}
  - CXX=${TRUE_CXX:-$CXX}

script:
- set -e && echo "CC is ${CC}, CXX is ${CXX}" && ${CC} --version
- make USE_LIBPFC=0
- ./uarch-bench --test-name=default/*
