language: cpp
sudo: false
branches:
  except:
    - /^(wip\/)?(appveyor|msvc|mingw|windows)(\-.+)?$/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &default_pacakges
      - nasm
      - gcc-4.9
      - g++-4.9
      
compiler:
  - gcc-4.9
  - g++-4.9      



before_install:
# The TravisCI framework will set CC and CXX after the env commands specified in the matrix are run, overwriting whatever
# we've specified there, so we need to reset them here. See also https://github.com/travis-ci/travis-ci/issues/6633 . 
  - CC=${TRUE_CC:-$CC}
  - CXX=${TRUE_CXX:-$CXX}

script:
- set -e && echo "CC is ${CC}, CXX is ${CXX}"
- make USE_LIBPFC=0
- ./uarch-bench --test-name=default/*
