language: cpp
sudo: false
branches:
  except:
    - /^(wip\/)?(appveyor|msvc|mingw|windows)(\-.+)?$/

matrix:
  include:
    # default travis gcc (currently 4.8.4) - doesn't support <regex>
    # - compiler: gcc busted
    # default travis clang (currently 5.0) - doesn't support <regex>
    - env: CXXFLAGS=-stdlib=libc++ CXX=clang
    
    # - env: CC_OVERRIDE=gcc-6 CXX_OVERRIDE=g++-6

before_install:
  - CXX=clangzz

script:
- echo "CXX is ${CXX}"
- make USE_LIBPFC=0
- ./uarch-bench --test-name=default/*
