language: cpp
sudo: false
branches:
  except:
    - /^(wip\/)?(appveyor|msvc|mingw|windows)(\-.+)?$/

addons:
  apt:
    sources: &default_sources
      - ubuntu-toolchain-r-test
    packages: &default_pacakges
      - linux-headers-generic
      - nasm
      - yasm
      
env:
  global:
    - GLOBAL=value



before_install:
# Travis will set CC and CXX after the env commands specified in the matrix are run, overwriting whatever
# we've specified there, so we need to reset them here. See also https://github.com/travis-ci/travis-ci/issues/6633 . 
  - CC=${TRUE_CC:-$CC}
  - CXX=${TRUE_CXX:-$CXX}

script:
- uname -a
- ls -l /lib/modules
- make
- ./uarch-bench --test-name=default/*
